/*
 SCRIPT SQL / BASE POSTGRES
 */

CREATE DATABASE gondorchic
  WITH ENCODING 'UTF8'
       LC_COLLATE 'fr_FR.UTF-8'
       LC_CTYPE 'fr_FR.UTF-8'
       TEMPLATE template0;

CREATE TABLE clients (
     id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     prenom       TEXT,
     nom          TEXT,
     pseudo       TEXT NOT NULL,
     mot_de_passe TEXT NOT NULL,

     CONSTRAINT uq_clients_pseudo UNIQUE (pseudo)
);

CREATE TABLE produits (
      id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      libelle     TEXT,
      prix        NUMERIC(10, 2),
      quantite    INTEGER,
      en_stock    BOOLEAN,
      image_link  TEXT
);

CREATE TABLE panier (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   INTEGER NOT NULL,
    produit_id  INTEGER NOT NULL,
    quantite    INTEGER NOT NULL,

    CONSTRAINT ck_panier_quantite_positive CHECK (quantite > 0),

    CONSTRAINT fk_panier_client
        FOREIGN KEY (client_id)
            REFERENCES clients (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    CONSTRAINT fk_panier_produit
        FOREIGN KEY (produit_id)
            REFERENCES produits (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

    CONSTRAINT uq_panier_client_produit UNIQUE (client_id, produit_id)
);