spring.application.name=magic-vente-stock

jwt.secret=ZGV2ZWxvcHBtZW50X3NlY3JldF9rZXlfc3VwZXJfc2VjdXJlXzEyMzQ1Njc4OTA=
jwt.expiration-ms=86400000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gondorchic
spring.datasource.username=postgres
spring.datasource.password=rabearison

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect